# The TCP port on which the server listens for client connections.
# Ensure this port does not conflict with other services.
# (default=12000)
port=12000

# The maximum time in milliseconds the server will wait for data from a client
# before closing the connection due to inactivity.
# (default=300000, which is 5 minutes)
socketTimeout=300000

# The maximum time in milliseconds the server will wait for various components
# (thread pools, schedulers, etc.) to terminate during a graceful shutdown.
# This value ensures services have enough time to persist data.
# (default=300000, which is 5 minute)
maxDelay=300000

# The maximum number of concurrent threads to handle client connections.
# A higher value allows more clients to be served simultaneously.
# (default=50)
maximumPoolSize=50

# The initial delay in minutes before the scheduled tasks (saving users and trades)
# run for the first time.
# (default=0, they start immediately)
initialDelaySchedule=0

# The interval in minutes between scheduled executions of the save tasks
# for users and trades.
# (default=1 minute)
rateSchedule=1

# The name of the JSON file used for user data persistence.
# (default=user.json)
userFileName=user.json

# The name of the JSON file used for trade history persistence.
# (default=storicoOrdini.json)
journalFileName=history.json

# The size of the Disruptor's RingBuffer. It must be a power of 2
# to ensure maximum performance.
# (default=256)
ringBufferSize=256