package it.cross.server.journal;

import it.cross.shared.Trade;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Manages the persistence of executed trades in a thread-safe and performant manner.
 * <p>
 * This class acts as a central repository for all trades generated by the order book.
 * To optimize for high-throughput scenarios, it employs a buffering strategy:
 * trades are first added to an in-memory list and then periodically written to a
 * persistent storage file in the background by a dedicated {@link ScheduledExecutorService}.
 */
public class TradeDB {

    private static final Logger logger = LoggerFactory.getLogger(TradeDB.class);
	private volatile static TradeDB instance;
	private final List<Trade> tradeList = new ArrayList<Trade>();
    private final ScheduledExecutorService scheduler;
    private final TradeStorage storage;
    private boolean isDirty = false;
    private final Object lock = new Object();
    private final int maxDelay;

	private TradeDB(String fileName, int initialDelaySchedule, int rateSchedule, int maxDelay) {
		this.scheduler = Executors.newSingleThreadScheduledExecutor();
        this.scheduler.scheduleAtFixedRate(new SaveTrade(this), initialDelaySchedule, rateSchedule, TimeUnit.MINUTES);
        this.storage = new TradeStorage(fileName);
        this.maxDelay = maxDelay;
        logger.info("TradeDB initialized with file: '{}'. Save task scheduled every {} minutes.", fileName, rateSchedule);
	}
	
    /**
     * This method uses a thread-safe, double-checked locking pattern with a
     * volatile instance variable to ensure that only one instance of TradeDB
     * is created.
     *
     * @param fileName             The name of the file for trade persistence.
     * @param initialDelaySchedule The delay before the first save task runs.
     * @param rateSchedule         The interval between subsequent save tasks.
     * @return The singleton TradeDB instance.
     */
    public static TradeDB getInstance(String fileName, int initialDelaySchedule, int rateSchedule, int maxDelay) {
        if (instance == null) {
            synchronized (TradeDB.class) {
                if (instance == null) {
					if (fileName == null || fileName.trim().isEmpty() || initialDelaySchedule < 0 || rateSchedule <= 0)
                        throw new IllegalArgumentException("A valid filename and positive schedule rates are required for TradeDB initialization.");
					instance = new TradeDB(fileName, initialDelaySchedule, rateSchedule, maxDelay);
                }
            }
        }
        return instance;
    }

    public static TradeDB getInstance() {
        if (instance == null)
            throw new IllegalStateException("TradeDB has not been initialized. Call getInstance(fileName, ...) first.");
        return instance;
    }
	
    /**
     * Persists the buffered trades to disk if any new trades have been added.
     * <p>
     * This method uses a fine-grained locking strategy to maximize concurrency.
     * It acquires a private lock only for the brief moment needed to copy the
     * current trades to a local list and clear the buffer. The slow file I/O
     * operation is then performed outside of the synchronized block, allowing
     * other threads (like the Disruptor) to continue adding new trades without
     * being blocked.
     */
	void saveTrade() {
		
        List<Trade> tradesToSave = null;
		synchronized (lock) {
            if (isDirty) {
                tradesToSave = new ArrayList<>(tradeList);
                tradeList.clear();
                isDirty = false;
            }
        }
		
		if (tradesToSave != null)
            try { storage.saveTrades(tradesToSave); } catch (IOException e) {
                logger.error("Failed to save trades to history file: ", e);
            }
		
	}
	
	public void addTrades(List<Trade> newTrades) {
		if (newTrades != null && !newTrades.isEmpty()) {
            synchronized (lock) {
            	Collections.sort(newTrades);
                tradeList.addAll(newTrades);
                isDirty = true;
            }
        }
    }
	
	public Map<Integer, List<Trade>> getHistory(String month) throws IOException{
		return storage.requestHistory(month);
	}
	
	/**
     * Ensures a graceful shutdown of the TradeDB service.
     * <p>
     * This method stops the background scheduler and waits for any in-progress
     * save task to complete. It then performs one final save operation to
     * ensure that any remaining trades in the buffer are persisted to disk,
     * preventing data loss.
     */
	public void shutdown(){
        scheduler.shutdown();
        try {
            logger.info("Waiting for TradeDB persistence scheduler to terminate...");
            if (!scheduler.awaitTermination(maxDelay, TimeUnit.MILLISECONDS)) {
                logger.warn("Scheduler did not terminate within the grace period. Forcing shutdown.");
                scheduler.shutdownNow();
            }
        } catch (InterruptedException e) {
            logger.warn("Shutdown of the scheduler was interrupted. Forcing shutdown.");
            scheduler.shutdownNow();
        }
        saveTrade();
        logger.info("TradeDB shutdown complete.");
    }
	
}
